### ISSUE TITLE
Changed readme.md and added a more detailed error output

### ISSUE THREAD

**Issue by LegendFabix** [Oh-Hell-Naw/UniConvert#1]
# Kleiner Vorschlag
## Readme.md
[README.md](https://github.com/DNAScanner/UniConvert/files/13438758/README.md)
Ändere mal die Readme.md um zu dieser, die sich hier im Anhang sich befindet.
## main.ts
Bei main.ts (Zeile 15) ändere die line zu: `console.log("No filename provided. Syntax is as following: <uniconvert> <path of image> <output format>")`, dass es auch jeder checkt.

**Comment by DNAScanner** [comment]
Hab abgeändert, danke
